version: '3.8'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
networks: 
  postgres-network:
    driver: bridge

