version: '2'
services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
